UMS/UMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from djrill import DjrillAdminSite

admin.site = DjrillAdminSite()
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='base.html')),

    # Examples:
    # url(r'^$', 'UMS.views.home', name='home'),
    # url(r'^UMS/', include('UMS.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include('userprofile.urls', namespace='profile')),
)

# Uncomment the next line to serve media files in dev.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

UMS/userprofile/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', profileDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/edit$', profileEdit.as_view(), name='edit'),

    url(r'^(?P<pk>\d+)/ablum$', profileAblum.as_view(), name='ablumList'),
    url(r'^(?P<pk>\d+)/ablum/(?P<ablum_pk>\d+)$', profileAblum.as_view(), name='ablum'),
    # # ex: /polls/5/
    # url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

UMS/userprofile/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from allauth.socialaccount.models import SocialAccount
import hashlib

from sorl.thumbnail import ImageField
import pytz

class UserProfile(models.Model):
    POSITION_CHOICES = (
        ('nb','New bird'),
        ('ju','Junior'),
        ('se','Senior'),
        ('ma','Manager'),
    )
    TIMEZONES = [(tz, tz) for tz in pytz.all_timezones]

    user = models.OneToOneField(User, related_name='profile')
    avator = ImageField(upload_to='user_profile_imgs')
    address = models.CharField(max_length=140, blank=True)
    phone_number = models.CharField(max_length=20)
    role = models.CharField(max_length=3, choices=POSITION_CHOICES, default='nb')
    timezone = models.CharField(max_length=30, choices=TIMEZONES, default='America/Los_Angeles')
 
    def __unicode__(self):
        return "{}'s profile".format(self.user.username)
 
    def get_field_values(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in UserProfile._meta.fields]

    def profile_image_url(self):
        if self.avator:
            return self.avator.url

        fb_uid = SocialAccount.objects.filter(user_id=self.user.id, provider='facebook')
        if len(fb_uid):
            return "http://graph.facebook.com/{}/picture?width=40&height=40".format(fb_uid[0].uid)
     
        return "http://www.gravatar.com/avatar/{}?s=100&d=wavatar".format(hashlib.md5(self.user.email).hexdigest())

    # def get_absolute_url(self):
    #     return reverse("npp/nonprofit_detail", kwargs={"slug": self.slug}) 

    class Meta:
        db_table = 'user_profile'

class Ablum(models.Model):
    owner = models.ForeignKey(UserProfile, related_name="ablum")
    image = ImageField(upload_to='user_ablum')

    def get_absolute_url(self):
        return reverse('profile:ablum', kwargs={
            'pk': self.owner.id,
            'ablum_pk': self.id    
        })

UMS/userprofile/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.utils import timezone

from braces.views import UserPassesTestMixin, LoginRequiredMixin, JSONResponseMixin, AjaxResponseMixin, CsrfExemptMixin
from .models import UserProfile, Ablum
from .form import UserProfileForm, UploaderForm

class hasAuthorized(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self, user):
        if long(user.profile.id) == long(self.kwargs['pk']):
            return True
        else:
            raise Http404

class profileDetail(LoginRequiredMixin, generic.DetailView):
    model = UserProfile
    template_name = 'profile/detail.html'

    def get_context_data(self, **kwargs):
        context = super(profileDetail, self).get_context_data(**kwargs)
        context['ablum'] = self.object.ablum.all()
        return context

class profileEdit(hasAuthorized, UpdateView):
    model = UserProfile
    template_name = 'profile/edit.html'
    form_class = UserProfileForm

    def get_success_url(self):
        return reverse("profile:detail", kwargs={"pk": self.kwargs['pk']}) 

    def get_context_data(self, **kwargs):
        context = super(profileEdit, self).get_context_data(**kwargs)
        context['ablum'] = self.object.ablum.all()
        return context

class profileAblum(JSONResponseMixin, AjaxResponseMixin, generic.View):
    def get_ajax(self, request, *args, **kwargs):
        json_dict = {
            'Hello': "World"
        }
        return self.render_json_response(json_dict)

    def post_ajax(self, request, *args, **kwargs):
        if request.POST['_method'] == 'DELETE':
            return self.delete_ajax(request, *args, **kwargs)

        form = UploaderForm(request.POST, request.FILES)
        if form.is_valid():
            upload = Ablum(
                owner=request.user.profile,
                image=request.FILES['upload']
            )
            upload.save()
        else:
            errors_dict = {}
            if form.errors:
                for error in form.errors:
                    e = form.errors[error]
                    errors_dict[error] = unicode(e)
                return self.render_json_response(errors_dict)

        return self.render_json_response({'success': True})

    def delete_ajax(self, request, *args, **kwargs):
        profile = get_object_or_404(UserProfile, pk=kwargs['pk'])
        ablum = get_object_or_404(profile.ablum, pk=kwargs['ablum_pk'])
        if request.user.profile != profile:
            raise Http404
        else:
            ablum.delete()
            return self.render_json_response({
                'success': True    
            })

UMS/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}UMS{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/UMS.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to UMS.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">UMS</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
              <li><a href="/accounts/logout">Logout</a></li>
              {% if user.profile %}
              <li><a href="{% url 'profile:detail' user.profile.id %}">Profile</a></li>
              {% endif %}
            {% else %}
              <li><a href="/accounts/signup">Signup</a></li>
              <li><a href="/accounts/login">Login</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      {# <h1>{% block page_title %}Example Base Template{% endblock page_title %}</h1> #}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'js/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'js/jquery.fileupload.js' %}"></script>
    <script src="{% static 'js/jquery.knob.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/UMS.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

UMS/templates/profile/base.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href='/static/css/style.css'/>
</head>
<body class="login_body">
{% block body %}

    {% if messages %}
        <div>
            <strong>Messages:</strong>
            <ul>
                {% for message in messages %}
                    <li>{{message}}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
{% endblock %}
{% block extra_body %}
{% endblock %}
</body>
</html>

UMS/templates/profile/detail.html
{% extends "profile/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-5">

      <img src="{{ object.profile_image_url }}"/>
      {% thumbnail object.avator "200" as im %}
        <img src="{{ im.url }}">
      {% endthumbnail %}
      <table>
        {% for name, value in object.get_field_values %}
            <tr>
                <td>{{ name }}</td>
                <td>{{ value }}</td>
            </tr>
        {% endfor %}
      </table>
      {% for item in ablum %}
        {% thumbnail item.image "200" as im %}
          <img src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{item.get_absolute_url}}</p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

UMS/templates/profile/edit.html
{% extends "profile/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-5">

      <form method="post" action="{% url 'profile:edit' userprofile.id %}" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
      </form>
      {% for item in ablum %}
        <ul>
        <li>
        {% thumbnail item.image "200" as im %}
          <img src="{{ im.url }}">
          
        {% endthumbnail %}
        <button class="deleteImage" data-url="{{item.get_absolute_url}}">Delete</button>
        </li>
        </ul>
      {% endfor %}
    </div>
  </div>
</div>


<form id="upload" method="post" action="{% url 'profile:ablumList' userprofile.id %}" enctype="multipart/form-data">
    <div id="drop">
        Drop Here

        <a>Browse</a>
        <input type="file" name="upload" multiple />
    </div>

    <ul>
        <!-- The file uploads will be shown here -->
    </ul>
</form>

{% endblock %}


{% block extra_js %}
<script type="text/javascript"> 
   $(function(){

        var ul = $('#upload ul');

        $('#drop a').click(function(){
            // Simulate a click on the file input button
            // to show the file browser dialog
            $(this).parent().find('input').click();
        });

        // Initialize the jQuery File Upload plugin
        $('#upload').fileupload({

            formData: [
                { name: 'csrfmiddlewaretoken', value: "{{csrf_token}}" }
            ],
            // This element will accept file drag/drop uploading
            dropZone: $('#drop'),

            // This function is called when a file is added to the queue;
            // either via the browse button, or via drag/drop:
            add: function (e, data) {

                var tpl = $('<li class="working"><input type="text" value="0" data-width="48" data-height="48"'+
                    ' data-fgColor="#0788a5" data-readOnly="1" data-bgColor="#3e4043" /><p></p><span></span></li>');

                // Append the file name and file size
                tpl.find('p').text(data.files[0].name)
                             .append('<i>' + formatFileSize(data.files[0].size) + '</i>');

                // Add the HTML to the UL element
                data.context = tpl.appendTo(ul);

                // Initialize the knob plugin
                tpl.find('input').knob();

                // Listen for clicks on the cancel icon
                tpl.find('span').click(function(){

                    if(tpl.hasClass('working')){
                        jqXHR.abort();
                    }

                    tpl.fadeOut(function(){
                        tpl.remove();
                    });

                });

                // Automatically upload the file once it is added to the queue
                var jqXHR = data.submit();
            },

            progress: function(e, data){

                // Calculate the completion percentage of the upload
                var progress = parseInt(data.loaded / data.total * 100, 10);

                // Update the hidden input field and trigger a change
                // so that the jQuery knob plugin knows to update the dial
                data.context.find('input').val(progress).change();

                if(progress == 100){
                    data.context.removeClass('working');
                }
            },

            fail:function(e, data){
                // Something has gone wrong!
                data.context.addClass('error');
            },

            done:function (e, data) {
                console.log(data)
            }

        });

        // Prevent the default action when a file is dropped on the window
        $(document).on('drop dragover', function (e) {
            e.preventDefault();
        });

        // Helper function that formats the file sizes
        function formatFileSize(bytes) {
            if (typeof bytes !== 'number') {
                return '';
            }

            if (bytes >= 1000000000) {
                return (bytes / 1000000000).toFixed(2) + ' GB';
            }

            if (bytes >= 1000000) {
                return (bytes / 1000000).toFixed(2) + ' MB';
            }

            return (bytes / 1000).toFixed(2) + ' KB';
        }

        // Delete ablum
        $('button.deleteImage').on('click', function(e){
            $.ajax({
              type: 'post',
              dataType: 'json',
              data: {"csrfmiddlewaretoken": "{{csrf_token}}", "_method":"DELETE" },
              url: $(this).data('url'),
              success: function(res){
                console.log(res)
              }
            })
        })

    });
</script>
{% endblock extra_js %}